#include<stdio.h>
#include<stdlib.h>
typedefstruct
{
intkey;
}element;
element*queue=NULL;
intrear=0,front=0,size=2;
voidcreate()
{
queue=(element*)malloc(size*sizeof(element));
}
voidcopy(element*start,element*end,element*nq)
{
while(start!=end)
{
*nq=*start;
nq++;
start++;
}
}
voidqueueFull()
{
element*nq;
nq=(element*)malloc(2*size*sizeof(queue));
intstart=(front+1)%size;
if(start<2)
copy(queue+start,queue+start+size-1,nq);
else
{
copy(queue+start,queue+size,nq);
copy(queue,queue+rear+1,nq+size-start);
}
front=2*size-1;
rear=size-2;
size*=2;
free(queue);
queue=nq;
}
voidenQueue(elementitem)
{
rear=(rear+1)%size;
if(front==rear)
{
queueFull();
rear=(rear+1)%size;
}
queue[rear]=item;

}
elementdeQueue()
{
elementitem;
if(front==rear)
{
item.key=-1;
returnitem;
}
front=(front+1)%size;
returnqueue[front];
}
voiddisplayQueue()
{
inti=front+1;
if(front==rear)
printf("\nTheQueueisempty\n");
else
{
printf("\n");
for(i=(front+1)%size;i!=(rear);i=(i+1)%size)
{
printf("%d",queue[i].key);
}
printf("%d",queue[i].key);
printf("\nfront=%d\trear=%d\n",front,rear);
}
}
intmain()
{
intchoice;
intn;
elementitem;
create();
do
{
printf("enterchoice\n");
printf("MENU\n");
printf("1.Insert\n2.Delete\n3.Display\n4.Exit\n");
scanf("%d",&choice);
switch(choice)
{
case1:printf("enterelement\n");
scanf("%d",&n);
item.key=n;
enQueue(item);
break;
case2:item=deQueue();
if(item.key==-1)
printf("queueisempty\n");

else
printf("elementdeletedis%d\n",item.key);
break;
case3:displayQueue();
break;

case4:printf("operationcomplete\n");

break;

default:printf("invalidchoice\n");

break;

}
}while(choice!=4);
}
