#include<stdio.h>
#include<stdlib.h>
typedefstructelement
{
intkey;
}element;
structqueue
{
elementdata;
structqueue*link;
};
typedefstructqueue*queuepointer;
queuepointerfront[10],rear[10];
voidenQueue(elementitem,inti)
{
queuepointertemp;
temp=(queuepointer)malloc(sizeof(structqueue));
temp->data=item;
if(front[i])
rear[i]->link=temp;
else
front[i]=temp;
rear[i]=temp;
rear[i]->link=NULL;
}
elementdeQueue(inti)
{
queuepointertemp;

temp=front[i];
elementitem;
if(front[i])
{
item=front[i]->data;
front[i]=front[i]->link;
}
else
{
item.key=-1;
}
free(temp);
returnitem;
}
voiddisplay(inti)
{
queuepointertemp;
temp=front[i];
if(front[i]==NULL)
{
printf("Queueisempty\n");
return;
}
printf("queue%dis\n",i+1);
for(;temp;temp=temp->link)
printf("%d\t",temp->data.key);
printf("\n");
}
intmain()
{
intchoice,queueno;
elementitem;
while(1)
{
printf("Enter\n1.Add\n2.Delete\n3.Display\n4.Exit\n");
scanf("%d",&choice);
if(choice!=4)
{
printf("Enterqueuenumberfrom1-10\n");
scanf("%d",&queueno);
}
switch(choice)
{
case1:printf("Enterdatatobeinserted:");
scanf("%d",&item.key);
enQueue(item,queueno-1);
break;

case2:item=deQueue(queueno-1);
if(item.key==-1)
printf("Queueempty\n");

else
printf("Elementdeleted:%d\n",item.key);
break;
case3:display(queueno-1);
break;

case4:printf("OperationComplete\n");

exit(0);

}
}
}
